version: "3.8"
services:
  symbol-service:
    image: symbol-service
    build:
      context: ./symbol-service
      dockerfile: ./docker/debug/Dockerfile
    ports:
      - "5000:8080"
      - "6000:8000"